services:
  - type: web
    name: cybersecurity-learning-platform
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      npm install
      npm run build
      flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://cyberlpdb_user:n7OkVwnHb61CNVISiDr8X6ucMbmxkgTo@dpg-csl75sggph6c73em22m0-a.oregon-postgres.render.com:5432/cyberlpdb
      - key: SECRET_KEY
        value: cyber