services:
  - type: web
    name: cybersecurity-learning-platform
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      npm install --prefix frontend
      npm run build --prefix frontend
      flask db upgrade
    startCommand: gunicorn "backend:create_app()"
