"""empty message

Revision ID: cbe699fd41bf
Revises: 4e5f37ba192c
Create Date: 2025-03-04 00:45:21.321859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe699fd41bf'
down_revision = '4e5f37ba192c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=255), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('reviews_course_id_fkey', type_='foreignkey')
        batch_op.drop_column('rating')
        batch_op.drop_column('course_id')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('reviews_course_id_fkey', 'courses', ['course_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('content')

    # ### end Alembic commands ###
