"""empty message

Revision ID: dad747c06679
Revises: 7318f114a0a9
Create Date: 2024-12-01 20:25:30.251615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad747c06679'
down_revision = '7318f114a0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Float(), nullable=False))
        batch_op.alter_column('classroom_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint('students_classroom_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key('students_classroom_id_fkey', 'classrooms', ['classroom_id'], ['classroom_id'])
        batch_op.alter_column('classroom_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
