<template>
  <v-container fluid class="onboarding-page-container">
    <v-row justify="center" align="center">
      <v-col cols="12" md="7">
        <v-card elevation="3" class="onboarding-card pa-6">
          <h2 class="section-title text-center">Finish Creating Your Teacher Account</h2>

          <v-form @submit.prevent="completeOnboarding" class="onboarding-form">
            <v-text-field
              v-model="classroomName"
              label="Classroom Name"
              outlined
              color="cyan-darken-2"
              :rules="[requiredRule]"
            />

            <v-text-field
              v-model="phoneNumber"
              label="Phone Number"
              placeholder="(xxx)xxx-xxxx"
              outlined
              color="cyan-darken-2"
              type="tel"
              :rules="[requiredRule, phoneFormatRule]"
            />

            <v-text-field
              v-model="schoolName"
              label="School Name"
              placeholder="Reno High"
              outlined
              color="cyan-darken-2"
              :rules="[requiredRule]"
            />

            <h4>Preferred Contact Method</h4>
            <v-radio-group v-model="preferredContactMethod" column color="cyan-darken-2">
              <v-radio label="Email" value="email" />
              <v-radio label="Phone" value="phone" />
            </v-radio-group>

            <h4>Create a Classroom ID</h4>
            <v-radio-group v-model="classIdChoice" column color="cyan-darken-2">
              <v-radio label="Randomly Generated Class ID" value="auto" />
              <v-radio label="Create My Own Class ID" value="custom" />
            </v-radio-group>

            <v-text-field
              v-if="classIdChoice === 'custom'"
              v-model="customClassId"
              label="Enter Custom Classroom ID"
              clearable
              outlined
              color="cyan-darken-2"
              :rules="[requiredRule, alphanumericRule]"
            />

            <v-text-field
              v-if="classIdChoice === 'auto'"
              :value="autoGeneratedClassId"
              label="Randomly Generated Class ID"
              outlined
              readonly
              color="cyan-darken-2"
            />

            <h4>Classroom Grade Level:</h4>
            <v-row>
              <v-col cols="6" v-for="grade in grades" :key="grade">
                <v-btn 
                  block 
                  :class="gradeLevel === grade ? 'grade-button-selected' : 'grade-button'" 
                  @click="gradeLevel = grade"
                >
                  {{ grade }}
                </v-btn>

              </v-col>
            </v-row>

            <v-btn 
              color="primary" 
              type="submit" 
              elevation="2" 
              class="submit-button"
              :disabled="!formIsValid"
            >
              <v-icon left>mdi-checkbox-marked-circle</v-icon>
              Complete
            </v-btn>
          </v-form>
        </v-card>
      </v-col>

      <!-- Image Column -->
      <v-col cols="12" md="5" class="text-center">
        <v-img :src="CyberPicture" alt="Cybersecurity Image" max-width="400" class="onboarding-image" />
      </v-col>
    </v-row>
  </v-container>
</template>

  
<script>
  //import { updateUserProfile } from '@/services/api';
  import CyberPicture from './CyberPicture.png';  // <-- dynamic image import
  import { updateLoginState } from '@/eventBus';

  export default {
    name: 'NewTeacherOnboarding',
    data() {
      return {
        CyberPicture,
        //rules
        requiredRule: v=> !!v || 'This field is required',
        phoneFormatRule: v => /^\(\d{3}\)\d{3}-\d{4}$/.test(v) || 'Phone Number must be in (xxx)xxx-xxxx format',
        // phoneFormatRule: v => /^\d{3}-\d{4}$/.test(v) || 'Phone Number must be in xxx-xxxx format',
        alphanumericRule: v => /^[a-zA-Z0-9]+$/.test(v) || 'ID must be alphanumeric',
        //
        username: '',
        email: '',
        role: '',
        firstName: '',
        lastName: '',
        classroomName: '',
        classroomNames: [],
        phoneNumber: '',
        schoolName: '',
        preferredContactMethod: 'email', // default value
        classIdChoice: 'auto', // default to "Generate Automatically"
        customClassId: '',
        autoGeneratedClassId: this.generateClassId(),
        gradeLevel: '',
        grades: ['9th grade', '10th grade', '11th grade', '12th grade'],
      };
    },
    computed: {
      formIsValid() {
        const isCustomClassIdValid = this.classIdChoice === 'custom' ? !!this.customClassId : true;
        const phoneValid = this.phoneFormatRule(this.phoneNumber) === true;
        return (
          this.firstName &&
          this.lastName &&
          this.classroomName &&
          phoneValid &&
          this.schoolName &&
          this.preferredContactMethod &&
          this.classIdChoice &&
          this.gradeLevel &&
          isCustomClassIdValid
        );
      },
    },
    created() {
      console.log('Loaded CyberPicture:', CyberPicture);

      //const userData = JSON.parse(localStorage.getItem('newUser')) || {};
      const email = this.$route.query.email;
      console.log('users email is:', email);
      const userInfo = JSON.parse(localStorage.getItem(email)) || {};
      console.log('Users Info is:', userInfo);   

      // this.username = userData.username || 'No username provided';
      // this.email = userData.email || 'No email provided';
      // this.role = userData.role || 'Teacher';
      this.firstName = userInfo.first_name || '';
      this.lastName = userInfo.last_name || '';
      this.email = userInfo.email || '';
      this.role = userInfo.role || '';
      this.autoGeneratedClassId = this.generateClassId();
    },
    methods: {
      generateClassId() {
        return 'CLS' + Math.random().toString(36).substring(2, 8).toUpperCase();
      },
      completeOnboarding() {
        if (!this.formIsValid) {
          alert('Please fill in all required fields correctly.');
          return;
        }

        const classId = this.classIdChoice === 'auto' ? this.autoGeneratedClassId : this.customClassId;
        const email = this.email;
        const userInfo = JSON.parse(localStorage.getItem(email)) || {};

        const updatedUser = {
          ...userInfo,
          classroomName: this.classroomName,
          phoneNumber: this.phoneNumber,
          schoolName: this.schoolName,
          preferredContactMethod: this.preferredContactMethod,
          gradeLevel: this.gradeLevel,
          classroomNames: [...(userInfo.classroomNames || []), { name: this.classroomName, id: classId }]
        };

        // Save updated user info under their email key
        localStorage.setItem(email, JSON.stringify(updatedUser));
        
        // Also save as current logged-in user
        localStorage.setItem('user', JSON.stringify(updatedUser));
        
        // Update login state (if using eventBus)
        if (typeof updateLoginState === 'function') {
          updateLoginState();
        }
        
        console.log('Updated user saved:', updatedUser);

        this.$router.push({ path: '/new-teacher-view', query: { email: email } });
      },
    },
  };
  </script>
  
  
  <style scoped>

  h4 {
    margin-bottom: 10px;
  }
  .onboarding-page-container {
    position: relative;
    background-color: #0a192f;
    background-image:
      radial-gradient(rgba(73, 216, 230, 0.1) 1px, transparent 1px),
      radial-gradient(rgba(0, 149, 237, 0.05) 2px, transparent 2px);
    background-size: 50px 50px, 70px 70px;
    background-position: 0 0, 25px 25px;
    min-height: 100vh;
    padding-top: 40px;
    padding-bottom: 60px;
    color: #e6f1ff;
  }
  
  .onboarding-card {
    background-color: #172a46;
    border-radius: 12px;
    border-left: 5px solid #64ffda;
    padding: 30px;
  }
  
  .section-title {
    font-size: 2rem;
    margin-bottom: 20px;
    color: #64ffda;
    text-shadow: 0 0 10px rgba(100, 255, 218, 0.3);
  }
  
  .onboarding-form {
    margin-top: 20px;
    color: #9cffe8;
  }
  
  .submit-button {
    background-color: #64ffda !important;
    color: #172a46 !important;
    font-weight: bold;
    margin-top: 20px;
    transition: transform 0.2s ease, box-shadow 0.2s ease;
  }
  
  .submit-button:hover {
    transform: translateY(-3px);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.3);
  }
  
  .onboarding-image {
    margin-top: 40px;
    margin-left: 90px;
    border-radius: 12px;
    margin-bottom: 120px;
  }

  .grade-button {
  background-color: #233554;
  color: #e6f1ff;
  font-weight: normal;
  transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.grade-button-selected {
  background-color: #64ffda;
  color: #172a46;
  font-weight: bold;
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(0,0,0,0.2);
}

.grade-button:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(0,0,0,0.2);
}

::v-deep .v-messages__message {
  color: #ff9393 !important;
}

  </style>
