<template>
  <v-layout class="rounded rounded-md">
    <v-app-bar color="surface-variant" title="Cybersecurity Learning Platform"></v-app-bar>
  </v-layout>
  
    <v-container fluid class="onboarding-container">
      <v-row class="d-flex align-center">
        <!-- Form Column on the left side -->
        <v-col cols="12" md="6">
        <v-card class="card-style"> 
          <h2>Finish Creating Your Teacher Account</h2>
  
          <!-- Teacher's first name -->
          <v-text-field
            v-model="firstName"
            label="First Name"
            variant="outlined"
            color="cyan-darken-2"
            class="hover-color"
            :rules="[requiredRule]"/>
  
          <!-- Teacher's last name -->
          <v-text-field v-model="lastName" label="Last Name" variant="outlined" color="cyan-darken-2" class="hover-color" :rules="[requiredRule]"/>
  
          <!-- Classroom name -->
          <v-text-field v-model="classroomName" label="Classroom Name" placeholder="1st Period" variant="outlined" color="cyan-darken-2" class="hover-color" :rules="[requiredRule]"  />
  
          <!-- Phone Number -->
          <v-text-field
            v-model="phoneNumber"
            label="Phone Number"
            placeholder="(xxx)xxx-xxxx"
            variant="outlined"
            color="cyan-darken-2" 
            class="hover-color"
            type="tel"
            :rules="[requiredRule, phoneFormatRule]"

          />
  
          <!-- School Name -->
          <v-text-field
            v-model="schoolName"
            label="School Name"
            placeholder="Reno High"
            variant="outlined"
            color="cyan-darken-2"
            class="hover-color"
            :rules="[requiredRule]"
          
          />
  
          <!-- Preferred Contact Method -->
          <v-row>
            <v-col cols="5"> 
              <h4>Preferred Contact Method</h4>
            </v-col>
            <v-col cols="5"> 
              <v-radio-group v-model="preferredContactMethod" column color="cyan-darken-2" >
                <v-radio label="Email" value="email" />
                <v-radio label="Phone" value="phone"/>
              </v-radio-group>
            </v-col>  
          </v-row>
  
          <!-- Classroom ID selection -->
          <v-row>
            <v-col cols="5"> 
              <h4>Create a Classroom ID</h4>
            </v-col>
            <v-col cols="7"> 
             <v-radio-group v-model="classIdChoice" column color="cyan-darken-2" >
                <v-radio label="Randomly Generated Class ID" value="auto" />
               <v-radio label="Create My Own Class ID" value="custom"/>
             </v-radio-group>
            </v-col>
          </v-row>

          <!-- Conditional textbox for custom classroom ID -->
          <v-text-field
            v-if="classIdChoice === 'custom'"
            v-model="customClassId"
            label="Enter Custom Classroom ID"
            placeholder="pizza4lunch"
            clearable
            variant="outlined"
            color="cyan-darken-2" 
            :rules="[requiredRule, alphanumericRule]"
          />
  
          <!-- Display generated classroom ID -->
          <v-text-field v-if="classIdChoice === 'auto'" :value="autoGeneratedClassId" label="Randomly Generated Class ID" outlined readonly color="cyan-darken-2"  />
  
          <!-- Grade Level selection -->
          <v-row>
          <div class="grade-selection">
            <h4>Classroom Grade Level:</h4>
            <v-row>
              <v-col cols="5" v-for="grade in grades" :key="grade">
                <v-btn block :color="gradeLevel === grade ? 'secondary' : 'blue-grey'" @click="gradeLevel = grade">
                  {{ grade }}
                </v-btn>
              </v-col>
            </v-row>
          </div>
         </v-row>

          <!-- Submit Button -->
          <v-btn color="green" @click="completeOnboarding" :disabled="!formIsValid">Complete
            <v-icon
              icon="mdi-checkbox-marked-circle"
              end
            ></v-icon>
          </v-btn>
        </v-card>
        </v-col>

        <!-- Image column on Right Side -->
        <v-col cols="12" md="6" class="text-center" color="cyan-darken-2" >
          <h3>Placeholder ui image</h3>
          <v-img src="https://via.placeholder.com/400x300" alt="Onboarding Image" />
        </v-col>
      </v-row>
    </v-container>
  </template>
  
  <script>
  export default {
    name: 'NewTeacherOnboarding',
    data() {
      return {
        //rules
        requiredRule: v=> !!v || 'This field is required',
        phoneFormatRule: v => /^\(\d{3}\)\d{3}-\d{4}$/.test(v) || 'Phone Number must be in (xxx)xxx-xxxx format',
        // phoneFormatRule: v => /^\d{3}-\d{4}$/.test(v) || 'Phone Number must be in xxx-xxxx format',
        alphanumericRule: v => /^[a-zA-Z0-9]+$/.test(v) || 'ID must be alphanumeric',
        //
        username: '',
        email: '',
        role: '',
        firstName: '',
        lastName: '',
        classroomName: '',
        classroomNames: [],
        phoneNumber: '',
        schoolName: '',
        preferredContactMethod: 'email', // Default value
        classIdChoice: 'auto', // Default to "Generate Automatically"
        customClassId: '',
        autoGeneratedClassId: this.generateClassId(),
        gradeLevel: '',
        grades: ['9th grade', '10th grade', '11th grade', '12th grade'],
      };
    },
    computed: {
      formIsValid() {
        // Check that all required fields are filled and the custom class ID is also filled if necessary
        const isCustomClassIdValid = this.classIdChoice === 'custom' ? !!this.customClassId : true;
        return (
          this.firstName &&
          this.lastName &&
          this.classroomName &&
          this.phoneNumber &&
          this.schoolName &&
          this.preferredContactMethod &&
          this.classIdChoice &&
          this.gradeLevel &&
          isCustomClassIdValid
        );
      },
    },
    created() {
      // Fetch user data from localStorage
      const userData = JSON.parse(localStorage.getItem('newUser')) || {};
      this.username = userData.username || 'No username provided';
      this.email = userData.email || 'No email provided';
      this.role = userData.role || 'Teacher';
      this.autoGeneratedClassId = this.generateClassId();
    },
    methods: {
      generateClassId() {
        return 'CLS' + Math.random().toString(36).substring(2, 8).toUpperCase();
      },
      completeOnboarding() {
        const classId = this.classIdChoice === 'auto' ? this.autoGeneratedClassId : this.customClassId;
        const newClassroom = {
          name: this.classroomName,
          id: classId,
        };
        this.classroomNames.push(newClassroom);

        // Save all the onboarding data to localStorage linked to the teacher's email
        const teacherData = {
          username: this.username,
          email: this.email,
          role: this.role,
          firstName: this.firstName,
          lastName: this.lastName,
          classroomNames: this.classroomNames,
          // classroomName: this.classroomName,
          phoneNumber: this.phoneNumber,
          schoolName: this.schoolName,
          preferredContactMethod: this.preferredContactMethod,
          // classId: this.classIdChoice === 'auto' ? this.autoGeneratedClassId : this.customClassId,
          gradeLevel: this.gradeLevel,

        };
  
        // Save data in localStorage (linked to teacher's email)
        const allTeachersData = JSON.parse(localStorage.getItem('teachersData')) || {};
        allTeachersData[this.email] = teacherData;
        localStorage.setItem('teachersData', JSON.stringify(allTeachersData));
  
        // Redirect to Teacher View page after completing onboarding
        this.$router.push('/new-teacher-view');
      },
    },
  };
  </script>
  
  <style scoped>
  h2 {
    color: rgb(71, 71, 71);
    padding: 30px;
  }

  h4 {
    color: rgb(71, 71, 71);
    padding: 10px 10px;
    text-align: left;
  }
  
  .grade-selection {
    color: rgb(80, 80, 80);
    padding: 30px;
    margin-top: 20px;
  }
  
  .onboarding-container {
    color: black;
    display: flex;
    padding: 30px;
    justify-content: space-between;
  }

  .card-style {
    width: auto;
    padding: 15px;

  }

  /* .hover-color:hover {
    color: #077887 !important;
    font-weight: bold;
    
  } */
  </style>
  