<template>
  <v-container class="onboarding-container">
    <v-row class="align-center justify-center">
      <!-- Welcome Panel -->
      <v-col cols="12" md="4" class="welcome-panel shadow">
        <div class="welcome-content">
          <h1 class="welcome-header">Welcome, {{ username }}!</h1>
          <p class="welcome-text">Let's set up your student profile.</p>
        </div>
      </v-col>
  
      <!-- Questionnaire Panel -->
      <v-col cols="12" md="6" class="questionnaire-panel shadow">
        <div class="progress-bar-container">
          <div
            class="progress-bar-fill"
            :style="{ width: progressPercentage + '%' }"
          ></div>
        </div>
  
        <transition name="fade">
          <div>
            <!-- Step Content -->
            <div v-if="currentStep !== null && !showStudentIdMessage" class="step-content">
              <h2 class="step-header">{{ currentQuestion }}</h2>
              <div class="step-options">
                <template v-if="currentOptions.length > 0">
                  <v-btn
                    v-for="(option, index) in currentOptions"
                    :key="index"
                    class="step-btn"
                    color="primary"
                    @click="handleOptionSelect(option)"
                  >
                    {{ option }}
                  </v-btn>
                </template>
                <template v-else>
                  <v-text-field
                    v-model="currentInput"
                    class="input-field"
                    label="Enter your answer"
                    outlined
                  />
                  <v-btn
                    class="submit-btn"
                    color="primary"
                    @click="handleInputSubmit"
                  >
                    Submit
                  </v-btn>
                </template>
              </div>
            </div>
  
            <!-- Confirmation Message -->
            <div v-if="showStudentIdMessage" class="confirmation-message">
              <h3 class="confirmation-text">
                Here's your unique student ID! Share it with others:
                <strong>{{ autoGeneratedStudentId }}</strong>
              </h3>
              <v-btn
                class="redirect-btn"
                color="success"
                @click="finishOnboarding"
              >
                Got it!
              </v-btn>
            </div>
          </div>
        </transition>
      </v-col>
    </v-row>
  </v-container>
</template>
  
<script>
import { updateUserProfile } from '@/services/api';

export default {
  name: "StudentOnboarding",
  data() {
    return {
      username: "",
      email: "",
      role: "",
      currentStep: 0,
      answers: {},
      currentInput: "",
      autoGeneratedStudentId: "", 
      showStudentIdMessage: false, 
      progressPercentage: 0,
    };
  },
  computed: {
    questions() {
      const baseQuestions = [
        { text: "Enter your first name", type: "input", key: "firstName" },
        { text: "Enter your last name", type: "input", key: "lastName" },
      ];
      return [
        ...baseQuestions,
        {
          text: "What's your grade level?",
          options: ["9th grade", "10th grade", "11th grade", "12th grade"],
          key: "gradeLevel",
        },
        {
          text: "Enter a class ID to join your classroom or skip.",
          options: ["Enter Classroom ID", "Skip Joining a Classroom"],
          key: "joinClassroomChoice",
        },
        {
          text: "Enter the classroom ID to join:",
          type: "input",
          key: "classroomId",
          optional: true,
        },
        {
          text: "Enter your school's name:",
          type: "input",
          key: "schoolName",
        },
      ];
    },
    currentQuestion() {
      return this.questions[this.currentStep]?.text || "Thank you for completing your profile!";
    },
    currentOptions() {
      return this.questions[this.currentStep]?.options || [];
    },
  },
  created() {
    const userData = JSON.parse(localStorage.getItem("newUser")) || {};
    this.username = userData.username || "New User";
    this.email = userData.email || "No email provided";
    this.role = userData.role || "Student";
  },
  methods: {
    handleOptionSelect(option) {
      const currentKey = this.questions[this.currentStep]?.key;
      if (currentKey === "joinClassroomChoice") {
        if (option === "Enter Classroom ID") {
          // Proceed to next step so user can enter classroom ID
          this.nextStep();
        } else if (option === "Skip Joining a Classroom") {
          this.answers["classroomId"] = "";
          this.updateLocalStorage("classroomId", "");
          this.nextStep();
        }
      } else {
        this.saveAnswer(option);
      }
    },
    handleInputSubmit() {
      if (this.currentInput.trim() !== "") {
        const currentKey = this.questions[this.currentStep]?.key;
        this.saveAnswer(this.currentInput.trim());
        this.currentInput = "";
        this.incrementProgress();

        if (currentKey === "schoolName") {
          this.autoGeneratedStudentId = this.generateStudentId();
          this.updateLocalStorage("student_id", this.autoGeneratedStudentId);
          this.showStudentIdMessage = true;
          this.currentStep = null;
        }
      }
    },
    saveAnswer(answer) {
      const currentKey = this.questions[this.currentStep]?.key;
      if (currentKey) {
        this.answers[currentKey] = answer;
        this.updateLocalStorage(currentKey, answer);
      }
      this.nextStep();
    },
    nextStep() {
      if (this.currentStep < this.questions.length - 1) {
        if (
          this.questions[this.currentStep + 1].key === "classroomId" &&
          this.answers["joinClassroomChoice"] === "Skip Joining a Classroom"
        ) {
          this.currentStep += 2;
        } else {
          this.currentStep++;
        }
      } else {
        this.currentStep = null;
        console.log("Profile completed:", this.answers);
      }
    },
    incrementProgress() {
      this.progressPercentage = Math.min(this.progressPercentage + 25, 100);
    },
    generateStudentId() {
      return "STU" + Math.random().toString(36).substring(2, 8).toUpperCase();
    },
    redirectToProfileView() {
      this.$router.push("/profileView");
    },
    updateLocalStorage(key, value) {
      const userData = JSON.parse(localStorage.getItem("newUser")) || {};
      userData[key] = value;
      localStorage.setItem("newUser", JSON.stringify(userData));
    },
    finishOnboarding() {
      const onboardingData = {
        first_name: this.answers.firstName || "",
        last_name: this.answers.lastName || "",
        grade_level: this.answers.gradeLevel || "",
        classroom_id: this.answers.classroomId || "",
        school_name: this.answers.schoolName || "",
        student_id: this.autoGeneratedStudentId,
      };
      const user = JSON.parse(localStorage.getItem("newUser")) || {};
      if (user && user.user_id) {
        updateUserProfile(user.user_id, onboardingData)
          .then(() => {
            const updatedUser = { ...user, ...onboardingData };
            localStorage.setItem("newUser", JSON.stringify(updatedUser));
            this.$router.push("/profileView");
          })
          .catch(error => {
            console.error("Error updating student profile:", error);
          });
      } else {
        console.error("No valid student found for onboarding update.");
      }
    },
  },
};
</script>

  
<style scoped>
.onboarding-container {
  padding: 20px;
  min-height: 100vh;
}
   
.welcome-panel {
  background: #e4e4e4; 
  color: rgb(0, 0, 0);
  border-radius: 12px;
  padding: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
}
  
.welcome-header {
  font-size: 28px;
  font-weight: bold;
  margin-bottom: 10px;
}
  
.welcome-text {
  font-size: 16px;
  line-height: 1.6;
}
  
.questionnaire-panel {
  background: white;
  border-radius: 12px;
  padding: 30px;
  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
}
  
.step-header {
  font-size: 24px;
  font-weight: bold;
  color: #1a202c; 
  text-align: center;
  margin-bottom: 20px;
}
  
.step-options {
  display: flex;
  flex-direction: column;
  align-items: center;
}
  
.step-btn {
  width: 80%;
  padding: 10px 20px;
  font-size: 18px;
  font-weight: bold;
  border-radius: 8px;
  margin: 10px 0;
  background-color: #3b82f6; 
  color: white;
  transition: background-color 0.3s;
}
  
.step-btn:hover {
  background-color: #2563eb; 
}
  
.input-field {
  width: 100%;
  margin-bottom: 20px;
}
  
.submit-btn {
  width: 100%;
  padding: 10px 20px;
  font-size: 16px;
  font-weight: bold;
  text-align: center;
  background-color: #3b82f6; 
  color: white;
  border-radius: 8px;
}
  
.submit-btn:hover {
  background-color: #2563eb; 
}
  
.confirmation-message {
  text-align: center;
  padding: 20px;
  background-color: #fefcbf;
  border-radius: 12px;
  margin-top: 20px;
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
}
  
.confirmation-text {
  font-size: 18px;
  font-weight: bold;
  color: #b45309;
}
  
.redirect-btn {
  padding: 10px 20px;
  margin-top: 20px;
  background-color: #10b981; 
  color: white;
}
  
.redirect-btn:hover {
  background-color: #059669; 
}
  
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.5s;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
.progress-bar-container {
  width: 100%;
  background-color: #e0e0e0; 
  border-radius: 8px;
  height: 12px;
  overflow: hidden;
  margin-bottom: 20px;
}
  
.progress-bar-fill {
  height: 100%;
  background-color: #4d76a4;
  transition: width 0.3s ease; 
}
</style>
