<template>
    <v-container class="onboarding-container">
      <v-row class="align-center justify-center">
        <!-- this is the welcome Panel -->
        <v-col cols="12" md="4" class="welcome-panel shadow">
          <div class="welcome-content">
            <h1 class="welcome-header">Welcome, {{ username }}!</h1>
            <p class="welcome-text">Let's set up your student profile.</p>
          </div>
        </v-col>
  
        <!-- beginning of Questionnaire Panel to help build user profile (changes based on role)-->
        <v-col cols="12" md="6" class="questionnaire-panel shadow">

          <div class="progress-bar-container">
            <div
              class="progress-bar-fill"
              :style="{ width: progressPercentage + '%' }"
            ></div>
          </div>         

          <transition name="fade">
            <div>
              <!-- steps stuff for tracking which question user is at, in the questionnaire -->
              <div v-if="currentStep !== null && !showStudentIdMessage" class="step-content">
                <h2 class="step-header">{{ currentQuestion }}</h2>
                <div class="step-options">
                  <template v-if="currentOptions.length > 0">
                    <v-btn
                      v-for="(option, index) in currentOptions"
                      :key="index"
                      class="step-btn"
                      color="primary"
                      @click="handleOptionSelect(option)"
                    >
                      {{ option }}
                    </v-btn>
                  </template>
                  <template v-else>
                    <v-text-field
                      v-model="currentInput"
                      class="input-field"
                      label="Enter your answer"
                      outlined
                    />
                    <v-btn
                      class="submit-btn"
                      color="primary"
                      @click="handleInputSubmit"
                    >
                      Submit
                    </v-btn>
                  </template>
                </div>
              </div>
  
              <!-- Confirmation Message -->
              <div v-if="showStudentIdMessage" class="confirmation-message">
                <h3 class="confirmation-text">
                  Here's your unique student ID! Share it with others:
                  <strong>{{ autoGeneratedStudentId }}</strong>
                </h3>
                <v-btn
                  class="redirect-btn"
                  color="success"
                  @click="redirectToProfileView"
                >
                  Got it!
                </v-btn>
              </div>
            </div>
          </transition>
        </v-col>
      </v-row>
    </v-container>
</template>
  
<script>
  export default {
    name: "StudentOnboarding",
    data() {
      return {
        username: "",
        email: "",
        role: "",
        currentStep: 0,
        answers: {},
        currentInput: "",
        autoGeneratedStudentId: "", 
        showStudentIdMessage: false, 
        progressPercentage: 0,
      };
    },
    computed: {
      questions() { //questions for the Student role users
        const baseQuestions = [
          { text: "Enter your first name", type: "input", key: "firstName" },
          { text: "Enter your last name", type: "input", key: "lastName" },
        ];
        return [
          ...baseQuestions,
          {
            text: "What's your grade level?",
            options: ["9th grade", "10th grade", "11th grade", "12th grade"],
            key: "gradeLevel",
          },
          {
            text: "Enter a class ID to join your classroom or skip.",
            options: ["Enter Classroom ID", "Skip Joining a Classroom"],
            key: "joinClassroomChoice",
          },
          {
            text: "Enter the classroom ID to join:",
            type: "input",
            key: "classroomId",
            optional: true,
          },
          {
            text: "Enter your school's name:",
            type: "input",
            key: "schoolName",
          },
        ];
      },
      currentQuestion() {
        return this.questions[this.currentStep]?.text || "Thank you for completing your profile!";
      },
      currentOptions() {
        return this.questions[this.currentStep]?.options || [];
      },
    },
    created() {
      const userData = JSON.parse(localStorage.getItem("newUser")) || {};
      this.username = userData.username || "New User";
      this.email = userData.email || "No email provided";
      this.role = userData.role || "Student";
    },
    methods: {
      handleOptionSelect(option) {
        const currentKey = this.questions[this.currentStep]?.key;
        if (currentKey === "joinClassroomChoice") {
          if (option === "Enter Classroom ID") {
            this.addClassroomIdStep();
          } else if (option === "Skip Joining a Classroom") {
            this.skipJoinClassroom();
          }
        } else {
          this.saveAnswer(option);
        }
      },
      handleInputSubmit() {
        if (this.currentInput.trim() !== "") {
          const currentKey = this.questions[this.currentStep]?.key;
          this.saveAnswer(this.currentInput.trim());
          this.currentInput = "";
          this.incrementProgress();

          if (currentKey === "classroomId" || currentKey === "schoolName") {
            this.autoGeneratedStudentId = this.generateStudentId();
            this.updateLocalStorage("student_id", this.autoGeneratedStudentId);
            this.showStudentIdMessage = true;
            this.currentStep = null;
          }
        }
      },
      saveAnswer(answer) {
        const currentKey = this.questions[this.currentStep]?.key;
        if (currentKey) {
          this.answers[currentKey] = answer;
          this.updateLocalStorage(currentKey, answer);
        }
        this.nextStep();
      },
      nextStep() {
        if (this.currentStep < this.questions.length - 1) {
          const nextQuestion = this.questions[this.currentStep + 1];
          if (
            nextQuestion.key === "classroomId" &&
            this.answers["joinClassroomChoice"] === "Skip Joining a Classroom"
          ) {
            this.currentStep += 2; 
          } else {
            this.currentStep++;
          }
        } else {
          this.currentStep = null;
          console.log("Profile completed:", this.answers);
        }
      },
      incrementProgress() {
        this.progressPercentage = Math.min(this.progressPercentage + 25, 100);
      },
      generateStudentId() {
        return "STU" + Math.random().toString(36).substring(2, 8).toUpperCase();
      },
      addClassroomIdStep() {
        const classroomIdStep = this.questions.find((q) => q.key === "classroomId");
        if (classroomIdStep && !this.answers["classroomId"]) {
          this.currentStep++;
        }
      },
      skipJoinClassroom() {
        const schoolNameStep = this.questions.find((q) => q.key === "schoolName");
        if (schoolNameStep && !this.answers["schoolName"]) {
          this.currentStep += 2;
        }
      },
      redirectToProfileView() {
        this.$router.push("/profileView");
      },
      updateLocalStorage(key, value) {
        const userData = JSON.parse(localStorage.getItem("newUser")) || {};
        userData[key] = value;
        localStorage.setItem("newUser", JSON.stringify(userData));
      },
    },
  };
</script>
  
<style scoped>
  .onboarding-container {
    padding: 20px;
    min-height: 100vh;
  }
   
  .welcome-panel {
    background: #e4e4e4; 
    color: rgb(0, 0, 0);
    border-radius: 12px;
    padding: 20px;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  
  .welcome-header {
    font-size: 28px;
    font-weight: bold;
    margin-bottom: 10px;
  }
  
  .welcome-text {
    font-size: 16px;
    line-height: 1.6;
  }
  
  .questionnaire-panel {
    background: white;
    border-radius: 12px;
    padding: 30px;
    box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
  }
  
  .step-header {
    font-size: 24px;
    font-weight: bold;
    color: #1a202c; 
    text-align: center;
    margin-bottom: 20px;
  }
  
  .step-options {
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  
  .step-btn {
    width: 80%;
    padding: 10px 20px;
    font-size: 18px;
    font-weight: bold;
    border-radius: 8px;
    margin: 10px 0;
    background-color: #3b82f6; 
    color: white;
    transition: background-color 0.3s;
  }
  
  .step-btn:hover {
    background-color: #2563eb; 
  }
  
  .input-field {
    width: 100%;
    margin-bottom: 20px;
  }
  
  .submit-btn {
    width: 100%;
    padding: 10px 20px;
    font-size: 16px;
    font-weight: bold;
    text-align: center;
    background-color: #3b82f6; 
    color: white;
    border-radius: 8px;
  }
  
  .submit-btn:hover {
    background-color: #2563eb; 
  }
  
  .confirmation-message {
    text-align: center;
    padding: 20px;
    background-color: #fefcbf;
    border-radius: 12px;
    margin-top: 20px;
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
  }
  
  .confirmation-text {
    font-size: 18px;
    font-weight: bold;
    color: #b45309;
  }
  
  .redirect-btn {
    padding: 10px 20px;
    margin-top: 20px;
    background-color: #10b981; 
    color: white;
  }
  
  .redirect-btn:hover {
    background-color: #059669; 
  }
  
  /* for smooth transition effects */
  .fade-enter-active, .fade-leave-active {
    transition: opacity 0.5s;
  }
  .fade-enter-from, .fade-leave-to {
    opacity: 0;
  }
  .progress-bar-container {
  width: 100%;
  background-color: #e0e0e0; 
  border-radius: 8px;
  height: 12px;
  overflow: hidden;
  margin-bottom: 20px;
}

.progress-bar-fill {
  height: 100%;
  background-color: #4d76a4;
  transition: width 0.3s ease; 
}
</style>